# config/secrets.yml
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #aws_secret: abcde
  #some_password: abcdex

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #aws_secret: abcde

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


#not_indented: key for all env in once
secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
